In [9]:
import numpy as np
import pandas as pd

In [10]:
df = pd.read_csv("../data/bangkok_traffy.csv")

In [11]:
df = df.drop(['organization','comment','photo','photo_after','coords','address','star','count_reopen'],axis=1)

In [12]:
df.head()

,ticket_id,type,subdistrict,district,province,timestamp,state,last_activity
0,2021-9LHDM6,{},บางพลัด,บางพลัด,กรุงเทพมหานคร,2021-09-01 10:44:55.353209+00,กำลังดำเนินการ,2022-02-22 04:59:58.622268+00
1,2021-FYJTFP,{ความสะอาด},NaN,NaN,กรุงเทพมหานคร,2021-09-03 12:51:09.453003+00,เสร็จสิ้น,2022-06-04 15:34:14.609206+00
2,2021-8GKAR9,{สายไฟ},สามเสนนอก,ห้วยขวาง,จังหวัดกรุงเทพมหานคร,2021-09-19 06:47:50.488685+00,กำลังดำเนินการ,2022-02-22 04:30:07.293416+00
3,2021-AFPUXZ,"{ถนน,สะพาน}",สีลม,บางรัก,กรุงเทพมหานคร,2021-09-19 07:40:30.000781+00,กำลังดำเนินการ,2022-02-22 04:30:04.507406+00
4,2021-CGPMUN,"{น้ำท่วม,ร้องเรียน}",หนองบอน,ประเวศ,กรุงเทพมหานคร,2021-09-19 14:56:08.924992+00,เสร็จสิ้น,2022-06-21 08:21:09.532782+00

In [13]:
df.isna().sum()

ticket_id        2658
type               97
subdistrict        72
district           74
province           25
timestamp           0
state               0
last_activity       0
dtype: int64

In [14]:
df['province'].unique()

array(['กรุงเทพมหานคร', 'จังหวัดกรุงเทพมหานคร', 'นนทบุรี', 'นครปฐม',
       'ศรีสะเกษ', 'สมุทรปราการ', 'เชียงใหม่', 'ปทุมธานี', 'สมุทรสาคร',
       'อ่างทอง', 'ชลบุรี', 'ภูเก็ต', 'ยะลา', 'ลำปาง', 'พระนครศรีอยุธยา',
       'ตาก', 'อุบลราชธานี', 'ฉะเชิงเทรา', 'ขอนแก่น', 'นครศรีธรรมราช',
       'เชียงราย', nan, 'จันทบุรี', 'สงขลา', 'นครราชสีมา', 'ปราจีนบุรี',
       'กาฬสินธุ์', 'พิจิตร', 'อุตรดิตถ์', 'ราชบุรี', 'กาญจนบุรี',
       'ชัยนาท', 'อุทัยธานี', 'สุพรรณบุรี', 'ลพบุรี', 'นครสวรรค์',
       'นครนายก', 'สกลนคร', 'สตูล', 'อุดรธานี', 'เพชรบุรี', 'ตรัง',
       'สุรินทร์', 'อำนาจเจริญ', 'บุรีรัมย์', 'สุโขทัย', 'สุราษฎร์ธานี',
       'พิษณุโลก', 'มหาสารคาม', 'ร้อยเอ็ด', 'แพร่', 'สมุทรสงคราม',
       'สิงห์บุรี', 'ลำพูน', 'ระยอง', 'ยโสธร', 'นครพนม', 'น่าน',
       'หนองบัวลำภู', 'จังหวัดชลบุรี', 'จังหวัดจังหวัด กรุงเทพมหานคร',
       'จังหวัดพระนครศรีอยุธยา', 'จังหวัดสมุทรปราการ', 'จังหวัดLac',
       'จังหวัดฉะเชิงเทรา', 'จังหวัดนนทบุรี', 'จังหวัดBangkok',
       'จังหวัดจังหวัดกรุงเทพมหานคร', 'ตราด', 'เพชรบูรณ์',
       'ประจวบคีรีขันธ์', 'จังหวัดปทุมธานี', 'จังหวัดสมุทรสาคร',
       'ปัตตานี', 'จังหวัดจ.ฉะเชิงเทรา', 'จังหวัดสระบุรี',
       'จังหวัดประจวบคีรีขันธ์', 'สระบุรี', 'จังหวัดลพบุรี', 'พะเยา'],
      dtype=object)

In [15]:
df = df[df['province'].str.contains('กรุงเทพ|bangkok',na=False,case=False)]

In [16]:
# df[df['type']=='{}'].time.value_counts()

In [17]:
df = df.dropna(subset=['subdistrict', 'district'] )

In [18]:
df.isna().sum()

ticket_id        2633
type               97
subdistrict         0
district            0
province            0
timestamp           0
state               0
last_activity       0
dtype: int64

In [19]:
df = df[df['state'].str.contains('เสร็จ',na=False,case=False)]

In [20]:
df.type.unique()

array(['{น้ำท่วม,ร้องเรียน}', '{สะพาน}', '{น้ำท่วม,ถนน}', ...,
       '{ถนน,จราจร,เสนอแนะ,ห้องน้ำ}',
       '{คนจรจัด,ความสะอาด,กีดขวาง,ทางเท้า,ร้องเรียน}',
       '{ถนน,ทางเท้า,PM2.5,ความปลอดภัย}'], dtype=object)

In [21]:
df.district.value_counts()

จตุจักร              10049
ประเวศ                8858
บางแค                 7816
บางเขน                6872
ลาดกระบัง             6615
บางกะปิ               6555
วัฒนา                 6406
คลองเตย               6080
สวนหลวง               5745
บางขุนเทียน           5136
บึงกุ่ม               4895
บางซื่อ               4719
ราชเทวี               4582
ปทุมวัน               4567
ดินแดง                4443
บางกอกน้อย            4360
ลาดพร้าว              4308
สาทร                  4292
บางรัก                4262
วังทองหลาง            4217
พญาไท                 4060
ธนบุรี                3986
บางนา                 3819
สายไหม                3797
พระนคร                3755
คลองสามวา             3735
มีนบุรี               3572
ห้วยขวาง              3481
บางพลัด               3434
ภาษีเจริญ             3426
สะพานสูง              3259
หนองจอก               3255
พระโขนง               3194
หลักสี่               3188
ดอนเมือง              3146
จอมทอง                3145
ตลิ่งชัน              2874
ทุ่งครุ               2733
หนองแขม               2732
ป้อมปราบศัตรูพ่าย     2701
ยานนาวา               2660
บางคอแหลม             2475
บางบอน                2432
คลองสาน               2230
ดุสิต                 2200
ราษฎร์บูรณะ           2084
คันนายาว              1974
ทวีวัฒนา              1972
บางกอกใหญ่            1598
สัมพันธวงศ์           1079
Name: district, dtype: int64

In [22]:
df[['subdistrict','district']]

       subdistrict     district
4          หนองบอน       ประเวศ
10         ยานนาวา         สาทร
25        ลาดพร้าว     ลาดพร้าว
64        ลาดพร้าว     ลาดพร้าว
102          ดุสิต        ดุสิต
...            ...          ...
270961        สีลม       บางรัก
270979     ทุ่งครุ      ทุ่งครุ
271016      ประเวศ       ประเวศ
271018   บางยี่ขัน      บางพลัด
271163    บางปะกอก  ราษฎร์บูรณะ

[202773 rows x 2 columns]

In [23]:
df['timestamp'] = pd.to_datetime(df['timestamp'], utc=True)
df['last_activity'] = pd.to_datetime(df['last_activity'], utc=True)

In [24]:
df['time'] =  (df['last_activity'] - df['timestamp']).dt.days

In [25]:
type_con = df['type'].str.strip('{}').str.get_dummies(',')

In [26]:
df = pd.concat([df,type_con],axis=1)

In [27]:
district_hot =  pd.get_dummies(df['district'])

In [28]:
df = pd.concat([df,district_hot],axis=1)

In [29]:
df = df.drop(['ticket_id','type','subdistrict','district','province','timestamp','state','last_activity'],axis=1)

In [30]:
df

,time,PM2.5,การเดินทาง,กีดขวาง,คนจรจัด,คลอง,ความปลอดภัย,ความสะอาด,จราจร,ต้นไม้,...,วัฒนา,สวนหลวง,สะพานสูง,สัมพันธวงศ์,สาทร,สายไหม,หนองจอก,หนองแขม,หลักสี่,ห้วยขวาง
4,274,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,252,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
25,245,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
64,456,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
102,165,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270961,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
270979,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
271016,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
271018,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
271163,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0